src/ZaminEducation.Data/Class1.cs, src/ZaminEducation.Data/IRepositories/IRepository.cs, src/ZaminEducation.Data/ZaminEducation.Data.csproj
=> DATA: IRepository.cs interface has been written.

src/ZaminEducation.Data/DbContexts/ZaminEducationDbContext.cs, src/ZaminEducation.Data/ZaminEducation.Data.csproj, src/ZaminEducation.Domain/Entities/Commons/Attachment.cs, src/ZaminEducation.Domain/Entities/Courses/Course.cs, src/ZaminEducation.Domain/Entities/Courses/CourseTarget.cs, src/ZaminEducation.Domain/Entities/Quizzes/Quiz.cs, src/ZaminEducation.Domain/Entities/UserCourses/Certificate.cs, src/ZaminEducation.Domain/Entities/UserCourses/CourseComment.cs, src/ZaminEducation.Domain/Entities/UserCourses/SavedCourse.cs, src/ZaminEducation.Domain/Entities/Users/UserSocialNetwork.cs
=> DATA: DbContext Has Been Written.

src/ZaminEducation.Api/Program.cs, src/ZaminEducation.Api/ZaminEducation.Api.csproj, src/ZaminEducation.Api/appsettings.json, src/ZaminEducation.Data/DbContexts/ZaminEducationDbContext.cs, src/ZaminEducation.Data/IRepositories/IRepository.cs, src/ZaminEducation.Data/Repositories/Repository.cs, src/ZaminEducation.Data/ZaminEducation.Data.csproj, src/ZaminEducation.Domain/Entities/Quizzes/QuizAsset.cs, src/ZaminEducation.Domain/Entities/Users/Region.cs
=> Repository created, Attachment dbSet added

src/ZaminEducation.Service/DTOs/CoursesDtos/CourseForCreationDto.cs, src/ZaminEducation.Service/DTOs/CoursesDtos/CourseModuleForCreationDto.cs, src/ZaminEducation.Service/DTOs/CoursesDtos/CourseTargetForCreationDto.cs, src/ZaminEducation.Service/DTOs/CoursesDtos/CourseVideoForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuestionAnswerForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizAssetForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizResultForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CertificateForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CourseCommentForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CourseRateForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/SavedCourseForCreationDto.cs, src/ZaminEducation.Service/DTOs/UsersDtos/AddressForCreationDto.cs, src/ZaminEducation.Service/DTOs/UsersDtos/RegionForCreationDto.cs, src/ZaminEducation.Service/DTOs/UsersDtos/UserForCreationDto.cs, src/ZaminEducation.Service/DTOs/UsersDtos/UserSocialNetworkForCreationDto.cs
=> SERVICE: Object Relations Changed To Id In DTOs

src/ZaminEducation.Api/Middlewares/ZaminEducationExceptionMiddleware.cs, src/ZaminEducation.Service/Helpers/HttpContextHelper.cs, src/ZaminEducation.Service/ZaminEducation.Service.csproj
Middleware is already created by whom?
=> ZS-5 | HttpContextHelper Is Created

src/ZaminEducation.Api/Middlewares/ZaminEducationExceptionMiddleware.cs, src/ZaminEducation.Api/Program.cs, src/ZaminEducation.Api/ZaminEducation.Api.csproj, src/ZaminEducation.Api/appsettings.json, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CourseCommentForCreationDto.cs
**SERILOG**
_I wrote serilog in the api layer but I didn't check it works because there is no Service and controller.  We can check the log at the end._
@MrTukhtaboev 
close #31
=> API: Written Serilog To Api Layer

src/ZaminEducation.Api/Extensions/ServiceExtensions.cs, src/ZaminEducation.Api/Program.cs, src/ZaminEducation.Data/Migrations/20220925122726_CourseVideoMigration.Designer.cs, src/ZaminEducation.Data/Migrations/20220925122726_CourseVideoMigration.cs, src/ZaminEducation.Domain/Entities/Courses/Course.cs, src/ZaminEducation.Service/Interfaces/ICourseService.cs, src/ZaminEducation.Service/Services/CourseService.cs
=> Additional Get Methods were written to Course entity

README.md, src/ZaminEducation.Api/Extensions/ServiceExtensions.cs, src/ZaminEducation.Domain/Configurations/PaginationMetaData.cs, src/ZaminEducation.Domain/Configurations/PaginationParams.cs, src/ZaminEducation.Service/Extensions/CollectionExtension.cs, src/ZaminEducation.Service/Interfaces/IQuizResultService.cs, src/ZaminEducation.Service/Services/CourseService.cs, src/ZaminEducation.Service/Services/QuizResultService.cs
=> SERVICE: `IQuizResultService.cs` was complited

src/ZaminEducation.Service/DTOs/Courses/CourseCategoryForCreationDto.cs, src/ZaminEducation.Service/DTOs/Courses/CourseForCreationDto.cs, src/ZaminEducation.Service/DTOs/Courses/CourseModuleForCreationDto.cs, src/ZaminEducation.Service/DTOs/Courses/CourseTargetForCreationDto.cs, src/ZaminEducation.Service/DTOs/Courses/CourseVideoForCreationDto.cs, src/ZaminEducation.Service/DTOs/Courses/HashTagForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuestionAnswerForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizAssetForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizContentForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizResultForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CertificateForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CourseCommentForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CourseRateForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/SavedCourseForCreationDto.cs, src/ZaminEducation.Service/DTOs/UsersDtos/AddressForCreationDto.cs, src/ZaminEducation.Service/DTOs/UsersDtos/RegionForCreationDto.cs, src/ZaminEducation.Service/DTOs/UsersDtos/UserForCreationDto.cs, src/ZaminEducation.Service/DTOs/UsersDtos/UserSocialNetworkForCreationDto.cs, src/ZaminEducation.Service/Mappers/MappingProfile.cs
=> SERVICE: DTO Lardagi Naming Errorlar To'g'irlandi

src/ZaminEducation.Data/DbContexts/ZaminEducationDbContext.cs, src/ZaminEducation.Data/Migrations/20220926194440_youtubeModelMigration.Designer.cs, src/ZaminEducation.Data/Migrations/20220926194440_youtubeModelMigration.cs, src/ZaminEducation.Domain/Entities/Courses/YouTubeVideo.cs, src/ZaminEducation.Service/Interfaces/IYouTubeService.cs, src/ZaminEducation.Service/Services/YouTubeService.cs, src/ZaminEducation.Service/ZaminEducation.Service.csproj
=> SERVICE: YouTube Service

src/ZaminEducation.Api/ZaminEducation.Api.csproj, src/ZaminEducation.Domain/Entities/UserCourses/Certificate.cs, src/ZaminEducation.Domain/Enums/CertificateLevel.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CertificateForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CertificateResultDto.cs, src/ZaminEducation.Service/Helpers/EnvironmentHelper.cs, src/ZaminEducation.Service/Interfaces/IAttachmentService.cs, src/ZaminEducation.Service/Interfaces/ICertificateService.cs, src/ZaminEducation.Service/Services/AttachmentService.cs, src/ZaminEducation.Service/Services/CertificateService.cs, src/ZaminEducation.Service/ZaminEducation.Service.csproj
=> Service: GenerateCertificate

src/ZaminEducation.Api/Middlewares/ConfigureApiUrlName.cs, src/ZaminEducation.Api/Middlewares/ZaminEducationExceptionMiddleware.cs, src/ZaminEducation.Api/Program.cs, src/ZaminEducation.Data/.config/dotnet-tools.json, src/ZaminEducation.Domain/Configurations/PaginationMetaData.cs, src/ZaminEducation.Domain/Configurations/PaginationParams.cs, src/ZaminEducation.Service/DTOs/Courses/CourseForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizAssetForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizForCreationDto.cs, src/ZaminEducation.Service/DTOs/QuizzesDtos/QuizResultForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CertificateForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CourseCommentForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/CourseRateForCreationDto.cs, src/ZaminEducation.Service/DTOs/UserCoursesDtos/SavedCourseForCreationDto.cs, src/ZaminEducation.Service/DTOs/UsersDtos/UserForCreationDto.cs, src/ZaminEducation.Service/Exceptions/ZaminEducationException.cs, src/ZaminEducation.Service/Extensions/CollectionExtension.cs, src/ZaminEducation.Service/Extensions/StringExtension.cs, src/ZaminEducation.Service/Helpers/FileHelper.cs, src/ZaminEducation.Service/Interfaces/ISavedCoursesService.cs, src/ZaminEducation.Service/Mappers/MappingProfile.cs, src/ZaminEducation.Service/Services/AttachmentService.cs, src/ZaminEducation.Service/Services/QuizResultService.cs, src/ZaminEducation.Service/Services/SavedCoursesService.cs
=> SERVICE: `SavedCoursesService.cs` Was Complited

src/ZaminEducation.Service/Extensions/AuditableExtention.cs, src/ZaminEducation.Service/Services/AttachmentService.cs
=> SERVICE: auditable Extention

src/ZaminEducation.Service/Services/AttachmentService.cs, src/ZaminEducation.Service/Services/CertificateService.cs, src/ZaminEducation.Service/Services/CourseCommentService.cs, src/ZaminEducation.Service/Services/CourseService.cs, src/ZaminEducation.Service/Services/QuizResultService.cs, src/ZaminEducation.Service/Services/SavedCoursesService.cs, src/ZaminEducation.Service/Services/YouTubeService.cs
=> SERVICE: GetAll Search Added

src/ZaminEducation.Service/Interfaces/IQuizService.cs, src/ZaminEducation.Service/Services/QuizService.cs, src/ZaminEducation.Service/Services/YouTubeService.cs
=> SERVICE: Added ```QuizService.cs``` CreateAsync, CreateAssetAsync, CreateAnswerAsync 

src/ZaminEducation.Service/Services/QuizService.cs
=> Quiz service bug fixed | #81

src/ZaminEducation.Api/Controllers/UsersController.cs, src/ZaminEducation.Api/Extensions/ServiceExtensions.cs, src/ZaminEducation.Api/ZaminEducation.Api.csproj, src/ZaminEducation.Service/Interfaces/IUserService.cs, src/ZaminEducation.Service/Services/UserService.cs
=> ZS-27 | Fixing Bugs

src/ZaminEducation.Api/Controllers/BaseController.cs, src/ZaminEducation.Api/Controllers/UsersController.cs, src/ZaminEducation.Api/Extensions/ServiceExtensions.cs, src/ZaminEducation.Api/Helpers/ConfigureApiUrlName.cs, src/ZaminEducation.Api/Program.cs, src/ZaminEducation.Data/Migrations/20220929085002_cascadeMuammosi.cs, src/ZaminEducation.Domain/Entities/Courses/Course.cs, src/ZaminEducation.Domain/Enums/CertificateLevel.cs, src/ZaminEducation.Service/DTOs/UserCourses/CertificateResultDto.cs, src/ZaminEducation.Service/Extensions/AuditableExtention.cs, src/ZaminEducation.Service/Interfaces/ICertificateService.cs, src/ZaminEducation.Service/Services/AuthService.cs, src/ZaminEducation.Service/Services/CourseService.cs, src/ZaminEducation.Service/Services/QuizResultService.cs, src/ZaminEducation.Service/Services/QuizService.cs, src/ZaminEducation.Service/Services/UserService.cs, src/ZaminEducation.Service/Services/YouTubeService.cs
Each class has its own function and each must be in its own folder. `ConfigureApiUrlName.cs` is not a middleware, it is a helper, so I put it in a separate folder.
close #93 
@MrTukhtaboev
=> API: Helper File Opened For `ConfigureApiUrlName.cs`

src/ZaminEducation.Service/Services/QuizService.cs
=> Quiz Get GetAll

src/ZaminEducation.Service/Interfaces/IQuizService.cs, src/ZaminEducation.Service/Services/QuizService.cs
=> Update and Delete methods in QuizService were added

src/ZaminEducation.Api/Controllers/UsersController.cs
=> Api: `UserController.cs` Authorization Fixed

src/ZaminEducation.Api/Controllers/CourseController.cs, src/ZaminEducation.Api/Controllers/UsersController.cs, src/ZaminEducation.Service/DTOs/Courses/CourseForCreationDto.cs, src/ZaminEducation.Service/Mappers/MappingProfile.cs, src/ZaminEducation.Service/Services/CourseService.cs
=> SERVICE: Fixed `CourseForCreationDto.cs` And `CourseService.cs`

src/ZaminEducation.Api/Controllers/CourseCommentController.cs, src/ZaminEducation.Api/Controllers/CourseController.cs, src/ZaminEducation.Service/Interfaces/ICourseCommentService.cs, src/ZaminEducation.Service/Interfaces/ICourseService.cs, src/ZaminEducation.Service/Interfaces/ISavedCoursesService.cs, src/ZaminEducation.Service/Interfaces/IUserService.cs, src/ZaminEducation.Service/Services/CourseCommentService.cs, src/ZaminEducation.Service/Services/CourseService.cs, src/ZaminEducation.Service/Services/QuizService.cs, src/ZaminEducation.Service/Services/SavedCoursesService.cs, src/ZaminEducation.Service/Services/UserService.cs
=> Service: Fixed Search

src/ZaminEducation.Api/Controllers/CourseController.cs, src/ZaminEducation.Api/Extensions/ServiceExtensions.cs, src/ZaminEducation.Api/Program.cs, src/ZaminEducation.Data/DbContexts/ZaminEducationDbContext.cs, src/ZaminEducation.Data/Migrations/20221005103322_referralLink.cs, src/ZaminEducation.Data/Migrations/ZaminEducationDbContextModelSnapshot.cs, src/ZaminEducation.Domain/Entities/UserCourses/ReferralLink.cs, src/ZaminEducation.Service/Interfaces/ICourseService.cs, src/ZaminEducation.Service/Services/CourseService.cs
=> ReferralLink Generate method added to CourseService.cs

src/ZaminEducation.Api/Controllers/AuthController.cs, src/ZaminEducation.Api/Controllers/CourseCommentController.cs, src/ZaminEducation.Api/Controllers/CourseController.cs, src/ZaminEducation.Api/Controllers/UsersController.cs, src/ZaminEducation.Api/Extensions/ServiceExtensions.cs, src/ZaminEducation.Domain/Entities/Courses/CourseCategory.cs, src/ZaminEducation.Service/Interfaces/ICourseCategoryService.cs, src/ZaminEducation.Service/Interfaces/ISavedCoursesService.cs, src/ZaminEducation.Service/Services/CourseCategoryService.cs, src/ZaminEducation.Service/Services/SavedCoursesService.cs
=> SERVICE&API: SavedCourseService And CourseCategoryService Has Been Written

src/ZaminEducation.Api/Controllers/HomePageController.cs, src/ZaminEducation.Api/ZaminEducation.Api.csproj
=> Landing Page Auth

Tests/ZaminEducation.Service.Unit/Services/Users/UserServiceTest.Add.cs, Tests/ZaminEducation.Service.Unit/Services/Users/UserServiceTest.Get.cs, Tests/ZaminEducation.Service.Unit/Services/Users/UserServiceTest.cs, Tests/ZaminEducation.Service.Unit/Services/YouTube/YoutubeServiceTest.Add.cs, Tests/ZaminEducation.Service.Unit/Services/YouTube/YoutubeServiceTest.cs, src/ZaminEducation.Api/Controllers/AuthController.cs, src/ZaminEducation.Api/Controllers/HomePageController.cs, src/ZaminEducation.Api/Controllers/UsersController.cs, src/ZaminEducation.Api/Controllers/ZCApplicantDirectionsController.cs, src/ZaminEducation.Api/Controllers/ZCApplicantsController.cs
=> Muhammadamin net/writing comments

src/ZaminEducation.Service/DTOs/Courses/CourseForCreationDto.cs, src/ZaminEducation.Service/Services/CourseService.cs, src/ZaminEducation.Service/Services/YouTubeService.cs
=> CODE RUB: Errors Have Been Fixed
